# Default values for serverless-analytics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides for name and fullname
#nameOverride: ""
#fullnameOverride: ""

# Spark configuration most of which goes into spark-defaults.conf
spark:
  version: 3.3.0

zeppelin:
  version: 0.10.1
  nginxVersion: 1.20.2
  dnsmasqImage: janeczku/go-dnsmasq:release-1.0.7
  service:
    port: 8080
  autorunParagraphIds: {}
